Repository open-sauced/pizza-verse, pull requests merged in 2023-10, with the labels that each got.

#22 fix: pizza-facts missing link to markdown file
  README.md
  pizza-facts-&-trivia.md
Labels: documentation

#25 feat: add information about New York City pizza
  regional-pizza.md
Labels: 💡 feature, hacktoberfest-accepted

#38 feat: add recipe for Indian Style pizza
  images/chicken-tikka-pizza.jpg
  pizza-recipes.md
  regional-pizza.md
Labels: 💡 feature, hacktoberfest-accepted

#44 feat: adding Buddy's Pizza
  images/six-mile.jpg
  regional-pizza.md
Labels: 💡 feature

#45 feat: Added trivia questions #4
  pizza-facts-&-trivia.md
Labels: good first issue, 💡 feature

#54 Update rules and steps to contribute in the README
  README.md
  pizza-facts-&-trivia.md
  pizza-recipes.md
  regional-pizza.md
  style-guide.md
Labels: documentation, 💡 feature

#56 Add a Resolving Merge Conflicts section to the README
  README.md
Labels: documentation, 💡 feature
